name: Deploy Superset Production

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-base.yml
    with:
      environment: prod
    secrets: inherit
    permissions:
      id-token: write
      contents: read
