name: Deploy Base

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  AWS_REGION: eu-west-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: publicaffairs-4-1-1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: eu-west-1


      # - name: Deploy to EC2
      #   run:
      #     ./yn-scripts/deploy.sh ${{ inputs.environment }}
